### ISSUE TITLE
The example folder is empty?

### ISSUE THREAD

**Issue by Yrr0r** [DuinOS/DuinOS#23]
Is there really an example as said in the readme.txt? Or I didn't get it correctly?

> Now, you can compile any standard project, but we suggest the \examples\DuinOS\MoreComplexBlinking deployed with DuinOS.

but in `/examples` , I can only find an empty folder `DuinOS`, is the file missing?

**Comment by carlosdelfino** [comment]
Hi, first of all I'm sorry for being away for so long, personal issues prevented me from taking care of the project. I am resuming work this month, with a new approach and I intend to release soon.

The examples are in this folder, but I used submodules to reference another repository and for some reason it didn't link.

In the repository available at the link below you can see the examples.

https://github.com/DuinOS/DuinOS-Examples
