### ISSUE TITLE
Port DuinOS for FGPArduino and Multicore Arduino, Message Queue and Share Memory (volatile)

### ISSUE THREAD

**Issue by carlosdelfino** [DuinOS/DuinOS#27]
Estou estudando o uso de multithreads em sistemas multi-core, e principalmente me interessa os mecanismos de troca de mensagens entre cores, compartilhamento de variáveis e outros efeitos colaterais.

Como não tenho posse de nenhuma placa que possua múltiplos cores como o Arduino Potenza H7, estou tentando achar uma forma de inserir um core a mais no FPGArduino, tarefa que não é trivial, inclusive já abri um issue no projeto oficial https://github.com/f32c/f32c/issues/91 quem puder fortalecer a solicitação será muito bom para nosso projeto.

**Comment by carlosdelfino** [comment]
I am studying the use of multithreads in multi-core systems, and I am mainly interested in the mechanisms for exchanging messages between colors, sharing variables and other side effects. As I do not have any board that has multiple colors like the Arduino Potenza H7, I am trying to find a way to insert an additional core in the FPGArduino, a task that is not trivial, I have already opened an issue in the official project f32c/f32c#91 whoever can strengthen the request will be very good for our project.

**Comment by racerxdl** [comment]
(sugestão) você poderia usar um ESP32 para o protótipo. É um processador 32 bit o qual você consegue compilar com GCC e tem dois núcleos rodando a 240MHz.

**Comment by carlosdelfino** [comment]
Obrigado pela dica @racerxdl, vou considerar tal uso, porém meu foco no momento é arquitetura Cortex-M, como estou estudando o Cortex-M23 e Cortex-M33, seria melhor para mim. O FPGA seria uma alternativa para tornar o projeto mais atraente quanto ao uso do Risc-V.

**Comment by carlosdelfino** [comment]
@racerxdl 
Pelo que li no datasheet do ESP32 nem todos são dual core, preciso estudar mais a fundo esta alternativa: https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf

**Comment by racerxdl** [comment]
Os single-cores são vendidos como ESP32-SOLO (e são bem incomuns na real). Eles são mais baratos que os Cortex M da vida.
https://produto.mercadolivre.com.br/MLB-1672105742-esp32-wroom-devkit-_JM

Ou se quiser pegar na china, ainda mais barato.
https://pt.aliexpress.com/item/4000106108116.html

**Comment by racerxdl** [comment]
Sobre alternativa com FPGA, eu to desenvolvendo um RISC-V em livestreams na twitch para rodar nessa placa: https://lucasteske.dev/2020/06/hacking-a-esp32-into-fpga-board

Ela custa na faixa de R$300 no mercado livre, e R$90 na china. 
https://produto.mercadolivre.com.br/MLB-1281934353-receiver-card-5a-hub-75b-colorlight-cl-color-light-_JM
https://pt.aliexpress.com/item/32281130824.html

Ela tem 4MB de ram e 2 portas gigabit ethernet (detalhes aqui https://github.com/racerxdl/chubby75/blob/master/5a-75b/hardware_V7.0.md ), porém vc precisa soldar os 4 fios ali no meio pra usar um JTAG ou um FT232R. A vantagem é que é um FPGA da Lattice que permite usar as ferramentas opensource de sintese (Yosis, Arachne-pnr etc...)

**Comment by carlosdelfino** [comment]
Ativei o recurso de forum/discussão para o repositório e abri uma thread  #29
